### ISSUE TITLE
UI thoughts for Bookmark Kind

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#48] opened 2016-04-01 06:57 UTC
Need an extra space between "Name/Title" and "Site Name/Publication/Album" when there is no other intervening text: 
![missing space](https://cloud.githubusercontent.com/assets/5882943/14199465/7cc78784-f799-11e5-844f-1cfd9152175a.PNG)

Could also add a space between author picture and author name. 

![spaces](https://cloud.githubusercontent.com/assets/5882943/14199676/553da76e-f79b-11e5-9b39-b1092c42dca4.PNG)

It would also be nice to have a space between the bookmark information and the summary blockquote. 

Similarly, is there a way to remove the <code>< hr ></code> underneath if the body tag for the post is empty with no actual content?

I'm loving post kinds more and more...

**Comment by dshanske** [comment] 2016-04-01 20:28
All of these make sense. Will implement.

**Comment by chrisaldrich** [comment] 2016-04-22 17:59
I've noticed that recently, within WordPress, adding a link to a WordPress page will generate a WordPress "content card" (http://www.wpbeginner.com/plugins/how-to-add-links-as-content-cards-in-wordpress/ presumably using Facebook open meta) that provide a title, snippet and photo in the **preview version** of a bookmark post where the summary text would typically appear, however when **published**, the card comes out instead as a simple linked title marked up as a blockquote within a blockquote.  Having the content card in a case like this is alright, but if it ultimately defaults to a linked version of the title, it's too redundant as it'll (almost always) be following a linked title which appears just above it.

![duplicate wp link](https://cloud.githubusercontent.com/assets/5882943/14750227/8967be74-0878-11e6-90ee-a762b8afddd3.PNG)

This only seems to happen for WordPress site-related bookmarks (presumably using Facebook open meta) and not other sites which default to showing the imported (Post Properties/Citation) summary field. Given options, I suppose most would prefer having only a standard text summary field which could contain text or be empty as preferred in one's case.

**Comment by dshanske** [comment] 2016-04-22 18:32
The issue is open as #42. Disable rich embeds

**Comment by chrisaldrich** [comment] 2017-02-03 01:56
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/48" class="u-in-reply-to"></a>I was recently playing around with this again. I noticed that in bookmarks (and possibly some other types) that including an author URL doesn't wrap the author(s) names with an <code>`<a class="microformats here" href="authorwebsite.com">Author name</a>`</code> as one might expect as a part of their h-card. 

Was this a conscious choice (in case there were multiple authors)? Or just overlooked?

**Comment by dshanske** [comment] 2017-02-03 02:41
I honestly don't recall. But stay tuned, I'll be looking at that code after the other plugins are settled down.

**Comment by dshanske** [comment] 2017-05-29 06:09
Writing a basic template for this to be released in the next version.

**Closed** 2017-05-29 06:09 UTC
