### ISSUE TITLE
Swarm checkins appear as notes

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#198] opened 2018-08-01 17:01 UTC
Perhaps I'm missing a setting somewhere, but since I've gotten <a href="https://ownyourswarm.p3k.io/" target="_blank" rel="noopener">OwnYourSwarm</a> working (using JSON as opposed to the "Simple" setting, the post data arrives as expected, however, Post Kinds is defaulting the post to be a <code>note</code> instead of a <code>checkin</code> as I would expect. (In general, I would think that all posts arriving from OYS would always default to be checkins despite the fact that they may have note-like content as well as photos.)

In the settings on my site, I've even got the "Default Kind for New Posts" set to <code>checkin</code>, as I use it often, yet the posts still show up as a note.

Ideas about what may be missing or going wrong?

As a small caveat, I'll note that this install is running Post Kinds Version 3.0.6, but I suspect that nothing has changed since about June that might fix or affect this issue.

(Originally published at https://boffosocko.com/2018/08/01/swarm-checkins-appear-as-notes/)

**Comment by metbril** [comment] 2018-08-02 17:17
I have this, too.

**Comment by metbril** [comment] 2018-08-02 18:57
I've done some testing. If you manually re-send a checkin from OYS, the post kind is 'checkin', but any automated post gets the 'note' kind.

If I change 'note' to 'checkin' I get this error message:

```
Notice: Undefined index: url in /home/xxx/domains/robertvanbregt.nl/public_html/wp/wp-content/plugins/indieweb-post-kinds.BAK/views/kind-checkin.php on line 13

Notice: Undefined index: name in /home/xxx/domains/robertvanbregt.nl/public_html/wp/wp-content/plugins/indieweb-post-kinds.BAK/views/kind-checkin.php on line 14
```

**Comment by metbril** [comment] 2018-08-02 19:00
After changing from note -> checkin -> note, the admin panel is loading fine (see #200).

**Comment by stephenpieper** [comment] 2018-08-05 20:18
Is there any fix for this? I'm getting the checkin errors too.

**Comment by stephenpieper** [comment] 2018-08-05 20:37
I'm using the JSON setting. The post gets set to "note" and the above errors appear instead of a link to the location. 

If I re-import the checkin from the OYS web site the post is formatted correctly but without any photos.

**Comment by metbril** [comment] 2018-09-08 18:30
JSON over here too

**Comment by dshanske** [comment] 2018-09-08 19:15
I am redoing a lot of this area due to inconsistent encoding between jf2 and mf2. Will see what happens.

**Comment by metbril** [comment] 2018-12-02 16:15
I have steadily (and/or stealthily) moved away from wordpress. So I won't be able to test this.

**Comment by Cambridgeport90** [comment] 2019-05-18 23:18
I'll let you know what happens once I test myself.

**Comment by dshanske** [comment] 2020-12-17 16:48
Is this still occurring? And does it occur only if you checkin with a photo or not?

**Comment by dshanske** [comment] 2021-01-22 12:55
I cannot reproduce this. Closing at this time due no further comments. Reopen if needed.

**Closed by dshanske** 2021-01-22 12:55 UTC
