### ISSUE TITLE
Parser error for http://worrydream.com/

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#145] opened 2018-01-09 21:47 UTC
When parsing this site's homepage I get the following error:

> Warning: Illegal string offset 'name' in /htdocs/website/wp-content/plugins/indieweb-post-kinds/includes/tabs/tab-author.php on line 14
> 
> Fatal error: Uncaught Error: Only variables can be passed by reference in /htdocs/website/wp-content/plugins/indieweb-post-kinds/includes/tabs/tab-author.php:14 Stack trace: #0 /htdocs/website/wp-content/plugins/indieweb-post-kinds/includes/tabs/tab-navigation.php(12): require_once() #&#8203;1 /htdocs/website/wp-content/plugins/indieweb-post-kinds/includes/class-kind-tabmeta.php(216): include_once('/homepages/32/d...') #&#8203;2 /htdocs/website/wp-admin/includes/template.php(1050): Kind_Tabmeta::display_metabox(Object(WP_Post), Array) #&#8203;3 /htdocs/website/wp-admin/edit-form-advanced.php(702): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post)) #&#8203;4 /htdocs/website/wp-admin/post-new.php(85): include('/homepages/32/d...') #&#8203;5 {main} thrown in /htdocs/website/wp-content/plugins/indieweb-post-kinds/includes/tabs/tab-author.php on line 14

The error causes the fields under the Author tab to not display and prevents other metaboxes below it on the page from displaying. Saving the post as a draft seems to clear the issue up. This looks to be a non-critical edge case of some sort, but thought I'd report it just in case there's something quirky it's catching. The website it's parsing appears to be handrolled, so the issue may stem from something odd there, though I'm not seeing anything too crazy.

Using the current repo version of Post Kinds and most other IW tech.

**Comment by dshanske** [comment] 2018-01-14 02:09
Can't reproduce this. I fixed that issue and pushed it.

**Comment by dshanske** [comment] 2018-09-21 16:46
Closed as cannot reproduce and parser now has its own repo

**Closed** 2018-09-21 16:46 UTC
