### ISSUE TITLE
3.1.1 text Array in quotes and Name

### ISSUE THREAD

**Issue by troutcolor** [dshanske/indieweb-post-kinds#231] opened 2018-10-15 17:49 UTC
Updated to 3.1.1

Quote replaced by text 'Array' in replies on my site 

eg:
http://johnjohnston.info/blog/augmented-eternity/

looks like it has happened to all of my replies and bookmarks:
http://johnjohnston.info/blog/kind/bookmark/

hmm not all ones for 2017 seems OK?

http://johnjohnston.info/blog/a-following-page-aka-some-significant-updates-to-my-blogroll/

<img width="662" alt="screen shot 2018-10-15 at 19 01 19" src="https://user-images.githubusercontent.com/2952893/46969042-ca319700-d0ac-11e8-9278-e15cc44c78a3.png">

cheers

john

**Comment by dshanske** [comment] 2018-10-15 18:33
That's strange, I can't reproduce this, but will do some checks. I found the other issues

**Comment by dshanske** [comment] 2018-10-15 18:39
I appreciate your willingness to test and figure out the issue. The code stores everything in an array as required, but is supposed to collapse it. All that code I changed was to standardize that.

**Comment by troutcolor** [comment] 2018-10-15 18:59
The least I can do. If you need me to try anything let me know.

**Comment by jgmac1106** [comment] 2018-10-16 11:00
@troutcolor I could not reproduce your bug either. I am wondering if thereis any theme customization that both you and Aaron share.

(Originally published at: http://jgregorymcverry.com/7933-2/)

**Comment by dshanske** [comment] 2018-10-16 11:18
Until I figure out what is different, it's hard for me to isolate it.

**Comment by troutcolor** [comment] 2018-10-16 11:40
@jgmac1106 I think Arron's problem is different than mine. His posts look ok compared to mine.

@dshanske anything that I can do? I use a child theme for sempress. I've deleted the kind_views.  I don't think there is anything else that would interfere?

**Comment by dshanske** [comment] 2018-10-16 11:58
It wouldn't be a theme. This is affecting the backend. But, a few possibilities. If you saved the data when it was corrupted, you might get this result. Saved as in updated an old post. The system doesn't change the database unless you update, with a few exceptions. That would be why, if you rolled back, it should revert.

In the old and new versions, most things are stored as arrays, which is why it says that. But the plugin collapses them for display. Which seems to work for others. So, the mystery now is what is different? Something with the PHP version possibly. Do you have access to the error logs to see if it says anything other than array to string conversion that might give me a clue?

If that doesn't work, I could always try going in and poking around myself if you want.

**Comment by troutcolor** [comment] 2018-10-16 12:31
@dshanske I rolled back to 3.0.9 and that fixed things except for a post I made this morning while using the 3.1.1 version. So it looks like the database is OK?
Here is the output of phpinfo
[phpinfo.pdf](https://github.com/dshanske/indieweb-post-kinds/files/2482969/phpinfo.pdf)

Which might help?

I don't have access to the php logs I did turn on WP_DEBUG and WP_DEBUG_LOG but nothing got saved to the log (permissions 666) ?
I've only got ftp access to the site. There is no cpannel. The server is OSX

**Comment by dshanske** [comment] 2018-10-16 12:36
It should work with 5.3. I run a compatibility checker for it. Do you want me to try to log in and look? I don't doubt it is the new code, but what about it is unique to you I can't figure out.

**Comment by troutcolor** [comment] 2018-10-16 12:37
@dshanske that would be good thanks? What do you need, an admin account? ftp?  where will I send it?

**Comment by dshanske** [comment] 2018-10-16 12:39
Just an admin account will do. Send it to my email. It's my firstname@lastname.com

**Comment by troutcolor** [comment] 2018-10-16 12:42
@dshanske sent. Many Thanks.

**Comment by dshanske** [comment] 2018-10-16 12:46
Will work on this tonight

**Comment by dshanske** [comment] 2018-10-16 12:46
I may upgrade it back and fiddle

**Comment by troutcolor** [comment] 2018-10-16 12:50
@dshanske fiddle away. Let me know anything I can do.

**Comment by pfefferle** [comment] 2018-10-16 14:01
@dshanske the php-mf2 library requires PHP 5.4 (at least the readme says so: https://github.com/microformats/php-mf2#v030)

You mentioned the PHPCS compatibility checker, but it seems that you exclude parse-this from the check and the php-mf2 lib is part of parse this...
`<exclude-pattern>*/includes/parse-this/*</exclude-pattern>`

**Comment by pfefferle** [comment] 2018-10-16 14:34
OK, the parse this code seems to be tested in a separate repo, but it does not really have unit tests... So even if the code might be 5.3 compatible, perhaps there might still be compatibility issues: http://php.net/manual/de/migration54.incompatible.php

**Comment by pfefferle** [comment] 2018-10-16 15:05
I tested php-mf2 with PHP5.3 https://travis-ci.com/pfefferle/php-mf2/jobs/152133356

**Comment by gRegorLove** [comment] 2018-10-16 16:03
Correct, php-mf2 requires 5.4+. https://github.com/microformats/php-mf2/issues/101

**Comment by dshanske** [comment] 2018-10-17 01:38
The plugin is parsing correctly, therefore it isn't a php-mf2 problem. I tried disabling all other plugins and it isn't any of them that I can see. Something is replacing the URL with h and all the properties with arrays and I'm not sure why.

**Comment by dshanske** [comment] 2018-10-17 01:43
@troutcolor The site is a bit slow at the moment. Do you experience problems of that nature?

**Comment by troutcolor** [comment] 2018-10-17 03:02
> @troutcolor The site is a bit slow at the moment. Do you experience problems of that nature?

It is not the fastest. Host was having problems around midnight UK time when server would really slow down for a while.

**Comment by dshanske** [comment] 2018-10-17 03:04
@troutcolor Would you be able to install a plugin called Post Meta Inspector? I don't have plugin capability as I would need your FTP password.

**Comment by troutcolor** [comment] 2018-10-17 03:14
> @troutcolor Would you be able to install a plugin called Post Meta Inspector? I don't have plugin capability as I would need your FTP password.

I’ve done that now. Thanks for the help.

**Comment by pfefferle** [comment] 2018-10-17 06:36
Then perhaps parts of your code aren‘t compatible with PHP 5.3. I think the only way to get sure is, to Unittest all critical parts.

**Comment by troutcolor** [comment] 2018-10-17 07:57
> The data structures are stored correctly in the database, even on the new ones.

Thanks for all your efforts. I think I'll roll back to 3.0.9 for now. Perhaps ask my host about upgrading php. Happy to try any suggestions, workarounds etc.

**Comment by dshanske** [comment] 2019-03-21 12:41
@troutcolor Any update on this?

**Comment by troutcolor** [comment] 2019-03-21 18:28
@dshanske I am waiting for my host to update the version of php so am still using version 3.0.9 

The update should happen at some point.

Cheers

john

**Comment by troutcolor** [comment] 2019-06-07 16:16
> @troutcolor Any update on this?

I am finally using 3.2.6 as my host moved me to server with php 7 all of the problems have vanished :-)

**Comment by dshanske** [comment] 2019-06-07 17:05
So we can close this.

**Closed by dshanske** 2019-06-07 17:05 UTC
